version: "3"
services:
  assistant:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: sh ./setup.sh
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - WIT_API=${WIT_API}
      - WEATHER_API=${WEATHER_API}
      - RAPID_API=${RAPID_API}
      - GOOGLE_API=${GOOGLE_API}
      - GOOGLE_MAP_API=${GOOGLE_MAP_API}
      - PLAYHT_API_AUTHORIZATION=${PLAYHT_API_AUTHORIZATION}
      - PLAY_API_USERID=${PLAY_API_USERID}
      - CHATGPT_OPENAI_KEY=${CHATGPT_OPENAI_KEY}
    ports:
      - "8024:8024"
    networks:
      - assistant-network
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: assistant
      MYSQL_USER: assistant
      MYSQL_PASSWORD: assistant
      MYSQL_ROOT_PASSWORD: assistant
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./db:/var/lib/mysql
      - /tmp/app/mysqld:/var/run/mysqld
    networks:
      - assistant-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Nginx:/etc/nginx/conf.d
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/live/:/etc/nginx/ssl/live/:rw
    depends_on:
      - assistant
    networks:
      - assistant-network
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - assistant-network
networks:
  assistant-network:
    driver: bridge
